#!/usr/bin/env bash
#
# Fetch the two third-party header trees this plugin compiles against.
#
# Neither is a git submodule, and that is deliberate:
#
#   - **obs-studio** is GPL-2.0. Its headers are all we need (we link against
#     the libobs that ships inside the user's own OBS.app), and vendoring ~5 MB
#     of GPL headers into this tree would put a second licence in the repo for
#     no benefit. A pinned shallow, sparse, blob-filtered clone is 13 MB and
#     takes about two seconds.
#   - **simde** is only needed because libobs's `util/sse-intrin.h` reaches for
#     `<simde/x86/sse2.h>` on any non-x86 target. On Apple Silicon that means
#     *every* libobs header pulls it in. obs-studio does not vendor it either;
#     its own CMake goes looking for it exactly like this.
#
# Both are pinned. Bump the tag here and nowhere else.
#
# Re-running is cheap and idempotent: an existing checkout at the right tag is
# left alone.

set -euo pipefail

OBS_TAG="32.1.2"
SIMDE_TAG="v0.8.2"

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
third_party="${root}/third_party"

mkdir -p "${third_party}"

# Shallow + sparse + blob:none. The sparse set is the smallest that compiles:
# `libobs` for the headers themselves, `cmake` for the obsconfig template we
# fill in below.
fetch() {
  local name="$1" url="$2" tag="$3"
  shift 3
  local dir="${third_party}/${name}"

  if [ -d "${dir}/.git" ]; then
    local have
    have="$(git -C "${dir}" describe --tags --always 2>/dev/null || echo unknown)"
    if [ "${have}" = "${tag}" ]; then
      echo "ok     ${name} ${tag}"
      return
    fi
    echo "stale  ${name} (${have} != ${tag}), refetching"
    rm -rf "${dir}"
  fi

  echo "fetch  ${name} ${tag}"
  git clone --quiet --depth 1 --branch "${tag}" --filter=blob:none --sparse \
    "${url}" "${dir}"
  git -C "${dir}" sparse-checkout set "$@"
}

fetch obs-studio https://github.com/obsproject/obs-studio.git "${OBS_TAG}" \
  libobs cmake
fetch simde https://github.com/simd-everywhere/simde.git "${SIMDE_TAG}" \
  simde

# libobs/obs-config.h includes <obsconfig.h>, which does not exist in the source
# tree — CMake generates it from cmake/templates/obsconfig.h.in when *obs* is
# built. A plugin build needs only the two unconditional defines from that
# template; every other entry is a `#cmakedefine` that is legitimately absent.
#
# Writing it here rather than from our CMakeLists keeps it beside the tree it
# belongs to, so the include path stays a single directory.
gen="${third_party}/obs-generated"
mkdir -p "${gen}"
cat > "${gen}/obsconfig.h" <<'EOF'
// Generated by scripts/bootstrap.sh — see the comment there for why this is
// hand-written rather than configured by CMake. Do not edit.
#pragma once

#define OBS_RELEASE_CANDIDATE 0
#define OBS_BETA 0
EOF
echo "ok     obsconfig.h"

echo
echo "third_party ready:"
du -sh "${third_party}"/* 2>/dev/null | sed "s|${root}/||"
